# Build settings
 
port: 4000
markdown:  kramdown
kramdown:
  parse_block_html: true
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Alejandro Del Vecchio"
description: "Powered by Jekyll and GitHub Pages"
author:      "Paul Le"
